
'''
!!! DO NOT EDIT THIS FILE !!!
'''
import random
from unit_1d_hw import *

def test_useless_function():
    assert useless_function() == None, f"Should return `{None}`, your function returned `{useless_function()}`"

def test_integer_return_5():
    assert integer_return_5() == 5, f"Should return `{5}`, your function returned `{integer_return_5()}`"

def test_string_return_I_am_a_string():
    assert string_return_I_am_a_string() == "I am a string!", f'Should return: "I am a string!", your function returned: {string_return_I_am_a_string()}'

def test_add_one():
    x = random.random()
    assert add_one() == x + 1, f"Should return `{x + 1}`, your function returned `{add_one()}`"


def test_add_x_y():
    x = random.randrange(-999, 999)
    y = random.randrange(-999, 999)
    assert add_x_y(x, y) == x + y, f"When x is {x}, and y is {y}, correct answer is {x+y}, but \
    your function returned {add_x_y(x, y)}"

def test_slope_intercept_function():
    m = random.randrange(-999, 999)
    x = random.randrange(-999, 999)
    b = random.randrange(-999, 999)
    assert slope_intercept_function(m, x, b) == m * x + b, f"Expected: {m * x + b} but your function returned: {slope_intercept_function(m, x, b)}"

def test_multi_return():
    x = random.randrange(-999, 999)
    y = random.randrange(-999, 999)
    assert len(multi_return(x, y)) == 2, f"multi_return must return 2 values, your function returned {len(multi_return(x, y))} values"
    x_out, y_out = multi_return(x, y)
    assert x_out == x * 5, f"The scaled x value should be: {x * 5}, but your scaled x value was {x_out}"
    assert y_out == y + 2, f"The incremented y value should be: {y + 2}, but your incremented y value was {y_out}"


def test_default_args():
    x_before_prepend = [5, 6, 7, 8, 9]
    assert default_args(x_before_prepend, 4) == [4, 5, 6, 7, 8, 9], f"Passed in {x_before_prepend} and 4, list returned should be {[4, 5, 6, 7, 8, 9]}, but your function returned {default_args(x_before_prepend, 4)}"
    assert default_args([7, 3, 2, 4, 1]) == [5, 7, 3, 2, 4, 1], f"Passed in just {[7, 3, 2, 4, 1]} with no prepend value (resorting to default), list returned should be {[5, 7, 3, 2, 4, 1]}, but got {default_args([5, 7, 3, 2, 4, 1])}"
